### ISSUE TITLE
Mismatch between CSS and TTML2 text align styling on <span>

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#238] opened 2017-01-26 17:51 UTC
TTML2 WD specifies _if a tts:textAlign attribute is specified on a span element, then that span element must be processed using inline block display semantics for the purpose of presentation processing_.

CSS however appears to apply inline block semantics (if specified using `display: inline-block`) only to lines that have been explicitly broken using `br`. See https://codepen.io/palemieux/pen/bgoLzb.

Do the CSS semantics apply here?

If so, this is an issue since this means http://www.w3.org/ns/ttml/profile/imsc1/extension/#multiRowAlign is not supported.

If not, this is an issue since there is no correspondence between CSS and TTML2. This should be brought to the attention of CSS WG, assuming this is a feature essential to the industry. In any case, a note should be added in TTML2.

**Comment by skynavga** [comment] 2017-02-04 20:36
Can you point to the specification text in CSS that justifies the following?

> CSS however appears to apply inline block semantics (if specified using display: inline-block) only to lines that have been explicitly broken using br.

**Comment by palemieux** [comment] 2017-02-04 21:24
> Can you point to the specification text in CSS that justifies the following?

There is nothing in the CSS [definition](https://www.w3.org/TR/CSS2/visuren.html#display-prop) of `inline-block` that indicates that `inline-block` applies to each line of the element to which `inline-block` is applied.

This is matched by the behavior of Firefox, Edge and Chrome.

**Comment by skynavga** [comment] 2017-02-04 21:42
On Sat, Feb 4, 2017 at 2:24 PM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> Can you point to the specification text in CSS that justifies the
> following?
>
> There is nothing in the CSS definition
> <https://www.w3.org/TR/CSS2/visuren.html#display-prop> of inline-block
> that indicates that inline-block applies to each line of the element to
> which inline-block is applied.
>
I think you misinterpret the meaning of inline block. All the content of
the element to which it applies constitutes the descendent content. That
is, the content of the inline block is layout out and lines are broken as
is the case with any block, and the result is an inline block area
containing one or more line area children. The presence or absence of <br/>
has no different semantics on this than is the case on a normal block.

**Comment by nigelmegitt** [comment] 2017-02-06 15:16
I may have the wrong end of this but I think @palemieux is referring to the fact that browsers treat lines generated by automatic wrapping differently from lines generated by manual line breaks, with no very obvious reason why, or any supporting specification. This seems to be independent of inline block display semantics.

For example https://w3c.github.io/imsc/imsc1/test/w3c/multiRowAlign/multiRowAlign1.html works when demonstrating multirowAlign but if you remove the line breaks it does not. It is not obvious why this is the case.

**Comment by palemieux** [comment] 2017-03-01 20:54
> I think you misinterpret the meaning of inline block. 

I wish it were only me (if it is the case), but all UAs do as well as illustrated in the codepen above.

**Comment by skynavga** [comment] 2017-05-24 23:54
OBE, since ``tts:textAlign`` no longer contains the language referenced in the initial comment of this issue. Therefore, I am closing this and marking works for me. However, since we still have a way to employ ``tts:textAlign`` with an inline block, namely, when ``tts:display="inlineBlock"``, then the initial comment may still apply in that case. If someone wants to propose an informative note by posting a PR that takes note of the (possibly unspecified) behavior of certain implementations of CSS, then please do so and re-open this issue.

**Comment by palemieux** [comment] 2017-05-25 00:01
This issue needs to be fixed. I plan to look at the new text and propose a PR as the case may be.

**Comment by palemieux** [comment] 2017-05-25 00:06
@nigelmegitt How do you expect multiRowAlign to work in TTML2?

**Comment by skynavga** [comment] 2017-05-25 00:16
Moving this out of Editor's WR List. When you post a PR, feel free to put it back.

**Comment by nigelmegitt** [comment] 2017-05-26 14:48
One option we have here is to add a note saying that nested elements with different `textAlign` values can be used to achieve complex line alignment, but in the case of `<span>`s the expected behaviour only occurs for specified line breaks; behaviour may vary when line breaks are inserted for example because `tts:wrapOption="wrap"`. And then call out that a consequence is not--always-perfect alignment with the multiRowAlign feature.

**Comment by palemieux** [comment] 2017-05-26 14:53
I am happy for IMSC2 to continue using ebutts:multiRowAlign .

**Comment by nigelmegitt** [comment] 2017-05-26 14:55
@palemieux my expectation is something along the lines of:

```xml
...
<p tts:textAlign="center">
   <span tts:display="inlineBlock" tts:textAlign="left">
      <span>First line</br>Second line</span>
   </span>
</p>
```

Would give a block of two lines left aligned to each other and centered horizontally in the region.

I would hope for a resolution that works when lines are broken automatically, but I think it would be acceptable albeit inferior if the solution only works with manual line breaks.

If there's a consistent way to do this in CSS then I'd like to know what it is.

Alternatively we could specify special semantics for TTML2 `tts:textAlign` on spans with inlineBlock that it explicitly applies to post-wrapping lines, and leave the rest to implementations to figure out. That way we get the equivalent of `multiRowAlign`.

**Comment by palemieux** [comment] 2017-05-26 14:58
@nigelmegitt The industry will have spent significant effort reaching interoperability around `ebutts:multiRowAlign`, I expect little interest to do it again with a different syntax, esp. if there is some figuring out to do.

**Comment by nigelmegitt** [comment] 2017-05-26 15:06
@palemieux That may be true however I do not think it is relevant at this stage. We should specify the semantics that we want in a way that is most compatible with XSL and CSS and allow industry the opportunity to feed back during WR and (based on implementations) in CR rather than second-guessing the response now.

If what we want is a better way to achieve the requirements of multiRowAlign then we should specify that. Nested elements with different alignment is much more elegant and fits better generally with the ecosystem. We should make it work if we can, or call out the limitations if we can accept them. It may be worth trading exact semantic equivalence with multiRowAlign in favour of easier implementation with CSS, for example, if it still works 95% of the time.

**Comment by palemieux** [comment] 2017-05-26 15:07
> If what we want is a better way to achieve the requirements of multiRowAlign then we should specify that. 

Who will do this?

**Comment by nigelmegitt** [comment] 2017-05-26 15:15
> Who will do this?

As far as I am concerned it is already done, the only outstanding issue I can see is the one you raised about non-explicit line break handling.

**Comment by skynavga** [comment] 2017-05-26 15:18
@palemieux says
>I am happy for IMSC2 to continue using ebutts:multiRowAlign

This issue and thread are relevant only for implementations of TTML that rely on the use of a CSS base formatter, yes? If that is so, then how does an implementation of ebutts:multiRowAlign that uses CSS obtain the desired results?

**Comment by skynavga** [comment] 2017-05-26 15:22
@nigelmegitt says
>Alternatively we could specify special semantics for TTML2 tts:textAlign on spans with inlineBlock that it explicitly applies to post-wrapping lines, and leave the rest to implementations to figure out.

I'm a bit confused since this always applies, i.e., alignment adjustments always apply after line breaking decisions are made. You imply this may not be the case on what basis?

**Comment by palemieux** [comment] 2017-05-26 15:23
>  If that is so, then how does an implementation of ebutts:multiRowAlign that uses CSS obtain the desired results?

It has to insert explicit `<br>` elements using JS to determine line breaks at time of rendering.

The issue here is that TTML2 does not explicitly supports `ebutts:multiRowAlign`, but instead uses a construct, which, when mapped to CSS, does not yield the expected outcome.

> As far as I am concerned it is already done, the only outstanding issue I can see is the one you raised about non-explicit line break handling.

Are you suggesting that authors must use explicit line breaks for multi-row align to work?

**Comment by skynavga** [comment] 2017-05-26 15:30
@palemieux correct me if I'm wrong, but I think you just said that existing implementations of ebutts:multiRowAlign **do** insert ``<br/>`` in order to work with existing CSS renderers

If that is so, then why couldn't implementations of display="inlineBlock" that use CSS renderers do the same thing? And, if they could, then is there a technical requirement here that TTML2 needs to address with respect to specifying inlineBlock semantics (since this depends on an implementation choice)?

**Comment by palemieux** [comment] 2017-05-26 15:35
> If that is so, then why couldn't implementations of display="inlineBlock" that use CSS renderers do the same thing?

Sure. As suggested in the original comment, at the very least, it should be noted that `display="inlineBlock"` does not in fact behave like `display: inline-block`. It would be good to note how this feature can be used to emulate `ebutts:multiRowAlign` since it is far from a direct mapping.

**Comment by skynavga** [comment] 2017-05-26 15:40
On Fri, May 26, 2017 at 9:35 AM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> If that is so, then why couldn't implementations of display="inlineBlock"
> that use CSS renderers do the same thing?
>
> Sure. As suggested in the original comment, at the very least, it should
> be noted that display="inlineBlock" does not in fact behave like display:
> inline-block. It would be good to note how this feature can be used to
> emulate ebutts:multiRowAlign since it is far from a direct mapping.
>
I'm still missing something: in what way does tts:display="inlineBlock"
differ from CSS display: inline-block?

Also, since TTX/TTPE do effectively use inline block semantics to implement
ebutts:multiRowAlign, then there is at least one existence proof. So we
have the option to draw on that to craft any necessary language not already
present or implied.

**Comment by palemieux** [comment] 2017-05-26 15:45
> I'm still missing something: in what way does tts:display="inlineBlock" differ from CSS display: inline-block?

See the example in the original comment. `display: inline-block` does not do what you might it does.

> Also, since TTX/TTPE do effectively use inline block semantics to implement ebutts:multiRowAlign, then there is at least one existence proof. 

TTPE does not use CSS.

**Comment by skynavga** [comment] 2017-05-26 16:09
On Fri, May 26, 2017 at 9:45 AM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> I'm still missing something: in what way does tts:display="inlineBlock"
> differ from CSS display: inline-block?
>
> See the example in the original comment. display: inline-block does not
> do what you might it does.
>
I take that to mean that existing CSS implementations do something (that is
not specified by CSS) that is counter to what one might expect (and that
isn't based on CSS specification language).

Also, since TTX/TTPE do effectively use inline block semantics to implement
> ebutts:multiRowAlign, then there is at least one existence proof.
>
> TTPE does not use CSS.
>
You said

It would be good to note how this feature can be used to emulate
> ebutts:multiRowAlign since it is far from a direct mapping.


which I took as a general statement unrelated to using CSS or not. Are you
specifically asking for specification language that describes mapping to
CSS? Would a brief note suffice that merely warns the reader of the CSS
situation without going into detail?

**Comment by palemieux** [comment] 2017-11-11 01:20
Joint CSS/TTWG meeting on 20171109 indicated that, by design, `display: inline-block` does not yield rendering equivalent to http://www.w3.org/ns/ttml/profile/imsc1/extension/#multiRowAlign

**Comment by skynavga** [comment] 2018-01-08 23:10
Based on discussion among myself, @cconcolato and @palemieux, propose removing support for ``inlineBlock`` as pertains to ``tts:textAlign``, which means removing application of ``tts:textAlign`` to spans. In addition, WG may wish to mark ``tts:{bpd,ipd}`` at risk in CR.

**Comment by nigelmegitt** [comment] 2018-01-10 02:45
That IRC log above included a resolution that the bot didn't spot because I didn't capitalise it:

RESOLUTION: WG is disposed to remove applicability of tts:textAlign to span and mark bpd, ipd and inline-block as "at risk" in the CR.

**Comment by palemieux** [comment] 2018-01-10 02:46
Commenter agrees with https://github.com/w3c/ttml2/issues/238#issuecomment-356483349

**Closed** 2018-01-30 06:26 UTC
Labels: WR-commenter-agreed, WR-resolved, discussed and agreed, pr open, substantive, wide review comment
