### ISSUE TITLE
Typo in <text-combine>, "auto" should read "all".

### ISSUE THREAD

**Issue by cconcolato** [w3c/ttml2#666] opened 2018-02-14 21:16 UTC
The [textCombine semantics](https://w3c.github.io/ttml2/#style-attribute-textCombine) use the value `all` and not `auto` while the [`<text-combine>`](https://w3c.github.io/ttml2/#style-value-text-combine) type defines only `auto`. The latter should be changed to use `all` for consistency and to align with CSS.

**Comment by nigelmegitt** [comment] 2018-02-15 14:22
I agree, it looks like we need to change `auto` to `all` in `<text-combine>`.

**Comment by skynavga** [comment] 2018-02-16 05:20
Looks like this was a copy/paste error.

**Comment by skynavga** [comment] 2018-05-11 20:26
Duplicate of #724. Closing.

**Closed by skynavga** 2018-05-11 20:26 UTC
Labels: duplicate

**Comment by nigelmegitt** [comment] 2018-05-14 12:57
Actually #724 was a duplicate of this, but let's not split hairs...
