### ISSUE TITLE
Default directions in mixed textOrientation should use TR50 

### ISSUE THREAD

**Issue by r12a** [w3c/ttml2#279] opened 2017-03-13 20:02 UTC
10.2.46 tts:textOrientation
http://w3c.github.io/ttml2/spec/ttml2.html#style-attribute-textOrientation

> If the value of this attribute is mixed, then, in vertical writing modes, glyphs from horizontal scripts are set sideways, i.e., 90° clockwise from their nominal orientation in horizontal text, while glyphs from vertical scripts are not affected.

The terms 'vertical scripts' and 'horizontal scripts' don't appear to have any definition.

I think this paragraph should actually say that the defaults specified in http://www.unicode.org/reports/tr50/ should be applied for mixed text.

Note that there are also implications for fullwidth Latin characters, and for punctuation, which don't appear to be captured by the text in the TTML spec.

**Comment by dae-kim** [comment] 2017-03-13 20:24
Duplicate of https://github.com/w3c/ttml2/issues/230

**Closed by dae-kim** 2017-03-13 20:24 UTC
Labels: duplicate, i18n-comment
