### ISSUE TITLE
Avoid populating non-applicable, non-inheritable styles in SSS(E).

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#213] opened 2016-10-30 21:15 UTC
_Specified Style Set Processing_ applies the initial value of styling attributes only when _P is not inheritable or E is the tt element_. There are however styling attributes that are inheritable and have initial values, e.g. color.

The prose also appears substantially different than that of TTML1, where _if the element type of E is the layout element type region, then set P′ to the initial value of property P_. 

Note: In the TTML1 case, it is not clear how initial values of non-inheritable styling attributes ever apply to elements other than regions.

**Comment by skynavga** [comment] 2016-10-31 19:21
> Specified Style Set Processing applies the initial value of styling attributes only when P is not inheritable or E is the tt element. There are however styling attributes that are inheritable and have initial values, e.g. color.

This is not a bug. Perhaps you don't recall that TTML2 introduces root style inheritance [1]. In particular, regions now inherit style from the root element (tt). As a consequence, all inheritable styles are initialized on tt and then inherited downwards toward region and thence to content elements.

[1] http://w3c.github.io/ttml2/spec/ttml2.html#semantics-style-inheritance-root

> The prose also appears substantially different than that of TTML1, where if the element type of E is the layout element type region, then set P′ to the initial value of property P.

That is correct. It has changed due to the introduction of root style inheritance which wasn't in TTML1.

> Note: In the TTML1 case, it is not clear how initial values of non-inheritable styling attributes ever apply to elements other than regions.

The description in TTML1 was incomplete in this regard. We already have an issue open to cover this need for a new erratum [2].

[2] https://github.com/w3c/ttml1/issues/200

**Comment by skynavga** [comment] 2016-10-31 19:22
Closing as this is not a bug or actionable issue.

**Comment by palemieux** [comment] 2016-10-31 22:08
> As a consequence, all inheritable styles are initialized on tt and then inherited downwards toward region and thence to content elements.

Ok. In 10.4.4.2(6.c), the initial value of non-inheritable P should not be applied to E if P does not apply to E, right?

In other words, shouldn't 10.4.4.2(6.c) read:

`if either (P is not inheritable and P applies to E) or (P is inheritable and E is the tt element), perform the following`

**Comment by skynavga** [comment] 2016-10-31 22:38
Well, at present, it is certainly logically correct, in the sense that the otherwise clause in 6(c) is the negation of the antecedent in 6(b) [by De Morgan's law]. Your proposed alternative is certainly not equivalent. However, I suppose your point is that step 6(c) should not set P' when E is not tt and P does not apply to E, since doing so would be redundant and unnecessarily inflate SSS(E). Yes?

**Comment by palemieux** [comment] 2016-10-31 22:41
>  However, I suppose your point is that step 6(c) should not set P' when E is not tt and P does not apply to E,
> since doing so would be redundant and unnecessarily inflate SSS(E). Yes?

Yes. Initial values of non-inheritable styles should not be applied to elements to which the style does not apply.

**Comment by skynavga** [comment] 2016-10-31 22:45
ok; that's an actionable point, which I'll address

**Closed** 2017-05-31 19:32 UTC
Labels: pr open
