### ISSUE TITLE
Should we allow more overhang for Chinese?

### ISSUE THREAD

**Issue by r12a** [w3c/ttml2#261] opened 2017-02-16 17:43 UTC
10.2.38 tts:rubyOverhangClass
https://www.w3.org/TR/2016/WD-ttml2-20161117/#style-attribute-rubyOverhangClass

> If the language of the base text is specified or can be inferred as Chinese or Korean, then auto should be interpreted as if the following were specified: ideographic.

I've [raised the question](https://github.com/w3c/clreq/issues/129) for Chinese with the cLReq folks, but from looking at the document, the rules seem less restrictive than Japanese.  TTML2 currently only allows overlap of `ideographic` and not of punctuation.

**Comment by palemieux** [comment] 2017-05-02 15:26
I could not find equivalents to tts:rubyOverhangClass and tts:rubyOverhang in the CSS specification.

**Comment by skynavga** [comment] 2017-05-02 19:50
@r12a

>TTML2 currently only allows overlap of ideographic and not of punctuation.

This is not correct. The author can specify an initial (default) value of a different overhang character set as desired, e.g.,

<pre>
&lt;initial tts:rubyOverhang="ideographic punctuationMarks"/&gt;
</pre>

I suggest this issue be closed (works for me).

**Comment by palemieux** [comment] 2017-05-03 23:48
@r12a Does the information at https://github.com/w3c/ttml2/issues/261#issuecomment-298741893 resolve your comment?

**Comment by r12a** [comment] 2017-05-08 15:52
> I could not find equivalents to tts:rubyOverhangClass and tts:rubyOverhang in the CSS specification.

@palemieux there are none.  Something along these lines should be added to a future level. The idea was to limit the content in level 1 to get it adopted sooner.

@skynavga the text i quoted relates to the `auto` setting. I know that the author can use a different approach if they want to, but i was wondering why the behaviour for Chinese and Korean is more restrictive than for Japanese when `auto` is set.  Unfortunately, there's no word from the CLReq folks.

**Comment by palemieux** [comment] 2017-05-09 17:26
@skynavga Can you answer the question _why the behaviour for Chinese and Korean is more restrictive than for Japanese when auto is set_?

**Comment by skynavga** [comment] 2017-05-10 15:45
Add punctuationMarks for Chinese/Korean base text. Resolved in 49ee8b475e9e53531445c1d97d8d351bb2a4e660.

**Comment by palemieux** [comment] 2017-05-10 16:07
Doesn't this need 3 day review?

**Comment by skynavga** [comment] 2017-05-10 16:24
No. It is a trivial semantic correction.

**Comment by palemieux** [comment] 2017-05-10 16:27
It is a change to conformance language, and approval from the commenter was not provided.

**Comment by skynavga** [comment] 2017-05-10 16:29
No approval from commenter is required to close an issue. If you have a substantive comment, then feel free to re-open; otherwise, I am closing and will continue to re-close this non PR fix.

**Comment by nigelmegitt** [comment] 2017-05-14 19:47
Sorry @skynavga I'm overruling you here: this is a normative semantic change that directly addresses a horizontal review comment. Reopening and requesting feedback from the issue raiser @r12a on whether or not 49ee8b4, i.e. the addition of punctuationMarks for Chinese/Korean base text does indeed resolve the issue to his satisfaction.

**Comment by skynavga** [comment] 2017-05-15 12:05
(1) there is no substantive comment left unaddressed; (2) lazy consensus means silence is consent; (3) this *is* a trivial change, much more trivial than the trivial change we presented to the director regarding changing the (already deployed) semantics of marker mode default value in TTML1 2ed; (4) 3 days of passe;

please do not re-open without a substantive comment

**Comment by r12a** [comment] 2017-05-15 13:20
Chaps, actually, in general, silence probably means that we just haven't had time to return to this issue yet (i'm out of the office today and last Friday, and was busy much of Thursday), since we're trying to track the changes as best we can, but have other stuff getting in the way.  However, it may help to know that we also track these issues ourselves, so whether you have or have not closed this issue here, we won't close https://github.com/w3c/i18n-activity/issues/342 until we've considered the outcome. (You'll see there, btw, that i'm currently proposing closure for this issue, and we'll probably take a decision on that next thursday.)

**Comment by skynavga** [comment] 2017-05-15 13:35
On Mon, May 15, 2017 at 7:20 AM, r12a <notifications@github.com> wrote:

> Chaps, actually, in general, silence probably means that we just haven't
> had time to return to this issue yet (i'm out of the office today and last
> Friday, and was busy much of Thursday), since we're trying to track the
> changes as best we can, but have other stuff getting in the way. However,
> it may help to know that we also track these issues ourselves, so whether
> you have or have not closed this issue here, we won't close
> w3c/i18n-activity#342 <https://github.com/w3c/i18n-activity/issues/342>
> until we've considered the outcome. (You'll see there, btw, that i'm
> currently proposing closure for this issue, and we'll probably take a
> decision on that next thursday.)
>
That's fine with me. If you should have a follow-on comment of a
technical/editorial nature, please re-open the issue.

**Comment by nigelmegitt** [comment] 2017-05-15 14:29
It is very much **not** okay with me to close this. It's fine to mark it with some kind of status to show "we think we're done editing this" but the issue being open/closed is a group tool not just an editing tool. 

Since this issue was raised by someone outside the group and it constitutes an item of wide review feedback that means that we have a process requirement both to dispose of that and to communicate that disposition back to the issue raiser, and to offer the opportunity for the issue raiser to comment one more time on that disposition. Until that process has been completed the issue is effectively open for the group (even if not for the Editor) and I will not allow this issue to be closed. Note that this has nothing to do with the substantive/normative/editorial/etc nature of the issue and the disposition. Similarly it is nothing to do with whether or not we have reached consensus within the group.

This is in some ways a limitation of the use of GitHub issues, which do not model state flows in a rich way, but right now it is the only tool we have to hand. Use a label to indicate that disposition is considered to be agreed, and filter such issues out if you want using `-LABEL:"disposition agreed"` or similar, but do not close the issue.

**Comment by skynavga** [comment] 2017-05-15 14:47
We have a conflict here. You think issues in github constitute a group tool, and I think the constitute an editor's tool. Again, there is no open comment on this issue, and there is no requirement to keep this open until the group accepts this result. So I am closing again. If you want to discuss this issue at the next call, then fine, we can do that. If there is a substantive reason to keep it open, then we can do so, but until then, there is no reason. Further, your continued protests about process are doing nothing but delaying progress. Is that your intent?

**Comment by nigelmegitt** [comment] 2017-05-15 15:57
The way I see it, continually discarding the view of the Chair and reopening the issue is creating noise and delay unnecessarily. Please move on with Editing work on other issues if you are done here @skynavga . I am assigning this to me to track disposition response.

**Comment by r12a** [comment] 2017-08-17 16:06
Thank you for considering this issue. The i18n WG is now closing the pointer to this issue in its review tracker.

**Comment by skynavga** [comment] 2017-08-21 15:12
I18N WG has accepted and closed this issue in their review tracker.

**Closed by skynavga** 2017-08-21 15:12 UTC
Labels: horizontal review comment, i18n-comment, pr merged
