### ISSUE TITLE
3D and images

### ISSUE THREAD

**Issue by mikedo** [w3c/ttml2#239] opened 2017-02-02 21:21 UTC
For tts:disparity to work with images, I think an image property is needed to signal left and right.

**Comment by skynavga** [comment] 2017-02-05 00:40
Please provide more detail and an visual example.

**Comment by mikedo** [comment] 2017-02-08 15:10
First, I assumed stereo applied to images as well as text.  Since the mid-1800's stereo images are required to be identified as "left" and "right", just like stereo moving pictures are (assuming human viewers with horizontally separated eyes :-)  Here's a visual example: 
![image](https://cloud.githubusercontent.com/assets/4533492/22742855/1fa81002-edcd-11e6-9296-b50cf8c5c200.png)
If you want to open discussion of whether TTML2 should support stereo images at all and what the rendering model is, that's a different issue I think.

**Comment by skynavga** [comment] 2017-02-08 15:27
Thanks. I grew up watching such images through a viewer. I think I have a
solution, which is to introduce the following named condition parameters:

   - stereoLeft
   - stereoRight
   - stereoNone

Then one could use as follows:

<image src="left.png" condition="parameter('stereoLeft')"/>
<image src="right.png" condition="parameter('stereoRight') ||
 parameter('stereoNone')"/>

or

<image src="left.png" condition="parameter('stereoLeft')"/>
<image src="right.png" condition="parameter('stereoRight')"/>
<image src="neutral.png" condition="parameter('stereoNone')"/>

**Comment by palemieux** [comment] 2017-02-08 15:33
> I think I have a solution, which is to introduce the following named condition parameters:

-1 for this approach. XML and TTML already has a time-tested means of introducing new parameters: through extension elements and attributes. Moreover, these are not "conditions", but rather intrinsic characteristics of the image: it is either a left image or a right image or unspecified.

**Comment by nigelmegitt** [comment] 2017-02-08 15:45
I think I understand where @skynavga is coming from here - the presentation context will know if it is generating an image intended for the left eye, the right eye, or both/none, so the specific image that is presented is conditional on this variable. That seems reasonable.

@palemieux what would kind of attribute would you use for this as an alternative?

**Comment by palemieux** [comment] 2017-02-08 15:53
@nigelmegitt My concerns are not with the vocabulary (stereoLeft, stereoRight and stereoNone), but with using the condition language instead of XML to express it. I think it can be done more simply using `tts:stereoImage=left|right|none`, just like `tts:disparity` for text.

**Comment by nigelmegitt** [comment] 2017-02-08 16:03
There is a conceptual difference here - whereas `tts:disparity` is used to tell a stereoscopic processor how to generate the left and right images, in this case that information is already encoded into the image and one image or the other needs to be selectively displayed - and not both at once.

I can see that both choices would work; using `tts:stereoImage` would effectively be a proxy for the conditional display semantics that are already present.

Are there any prior examples where the semantic exists in other places that we could use for reference or inspiration?

**Comment by mikedo** [comment] 2017-02-08 20:40
Stimulating discussion.  Yes, this is fundamentally a property of the image file; i.e. TTML cannot assert "left" if it is in fact the "right" image (the property is a bit like HDR images).  Another approach might be to simply make a "stereo-association" between two images and then defer the left/right property from the image metadata during decode.

The one image at a time model is too over-constraining. For example, it should work in VR glasses (two displays, simultaneous display).

SMPTE Digital Cinema (ST428-7) supports stereo image subtitles. I haven't studied this part.

**Comment by skynavga** [comment] 2017-02-08 21:32
On Wed, Feb 8, 2017 at 8:33 AM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> I think I have a solution, which is to introduce the following named
> condition parameters:
>
> -1 for this approach. XML and TTML already has a time-tested means of
> introducing new parameters: through extension elements and attributes.
> Moreover, these are not "conditions", but rather intrinsic characteristics
> of the image: it is either a left image or a right image or unspecified.
>
First, the use of @condition is XML, so please don't mischaracterize it.
Second, we already have a condition parameter ''forced' used to alter
presentation based on processor state. Third, the stereo display state is
just another form of processor state, and here the semantics are to switch
between or switch on/off an image based on this state, so it is exactly in
line with the anticipated usage. Finally, the syntactic, semantic, and
schema overhead of introducing a new tts:* attribute is much higher than
simply defining a new named parameter. These semantics are precisely what
@condition was designed to handle.

So I'm sticking with my proposed solution.

**Comment by mikedo** [comment] 2017-02-08 21:41
I do not agree it is a processor state.  Please see my post just above yours about simultaneous display.

**Comment by skynavga** [comment] 2017-02-08 21:48
It is a processor state in the sense that at any given time, the
presentation processor is constructing a rendering of the content for a
specific stereo state, and the output is one rendering per stereo state.

**Comment by skynavga** [comment] 2017-02-08 21:59
I might be persuaded to add a local @stereo attribute to tt:image, with
values left|right|both|none or something of that nature. As MD points out,
this information would ideally be supplied by the image itself, but since
PNG/JPEG don't have a standard way to do this (as far as I know), then we
could supplant that data directly on tt:image.

I don't want this to be a @tts:* property since it is unrelated to
everything except images.

We could also, in addition, define the condition named parameters as well,
which would be convenient for switching between non-image content
alternatives or even larger groups of content/styling based on processor
stereo rendering state.

**Comment by mikedo** [comment] 2017-02-08 22:02
That POV presumes a specific hardware architecture that I don't think is so far constrained in TTML.  For example although many presentation engines might render each glyph or each image in the same synchronic document serially, I don't see why a multicore processor can't do things simultaneously and conform to TTML.

**Comment by skynavga** [comment] 2017-02-08 22:16
No, it doesn't assume a hardware dependency at all, that is, unless you are
thinking one would implement the entire TTML layout/rendering engine in
hardware. My assumption is that this engine is, in general, software based,
and whenever it is constructing a rendering for a given ISD, it knows which
stereo image it is constructing. If this were not the case, then it
wouldn't know how to apply a tts:disparity value, would it?

**Comment by mikedo** [comment] 2017-02-08 22:33
Glenn, I think we're out of sync on our posts.  Let's explore things other than condition.  FYI, I am not happy about tts: either - tts: generally alters the presentation which is not like this. 

I think we have to signal both left and right and the pairing - a left image can't be paired with a random other right image in the document. Or can there only one pair of stereo images in any synchronic document? Hence my suggestion earlier about "stereo association".

But maybe we should consider a stereo image object - perhaps a wrapper like the MPEG image file format that has both images bound in one wrapper with left/right metadata? I.e. maybe it's just not a TTML layer problem to solve the pairing and L/R?

**Comment by skynavga** [comment] 2017-02-08 22:38
Let's put this on the agenda for an upcoming call. More real-time is needed.

**Comment by mikedo** [comment] 2017-02-08 22:48
Agreed.  If you update the spec for some other reason, maybe add a note of the form: "Note: stereo image signaling is still under study."  Just in case someone takes the PWD and tries to implement it.

**Comment by nigelmegitt** [comment] 2017-02-09 09:16
> Let's put this on the agenda for an upcoming call. More real-time is needed.

Since this is actively being discussed I'm happy to put it on today's call if the main contributors are able to  attend.

**Comment by palemieux** [comment] 2017-02-10 22:03
An important data point for this discussion: in D-Cinema (SMPTE ST 428-7), the same image is used for both left and right eyes, using a tts:disparity-like parameter to laterally offset the center of the image in each eye. As a result the image can only appear in a single plane, but that seems to be sufficient and is readily supported by tts:disparity. So perhaps the ability to have full stereoscopic images as suggested in this issue is in addition to what is already supported by the latter.

**Comment by palemieux** [comment] 2017-02-10 22:04
@skynavga What about `@srcLeft` and `@srcRight` attributes in addition to `@src` in `image` elements?

**Comment by skynavga** [comment] 2017-02-11 00:27
On Fri, Feb 10, 2017 at 3:04 PM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> @skynavga <https://github.com/skynavga> What about @srcLeft and @srcRight
> attributes in addition to @src in image elements?
>
I was thinking more like adding @stereo to tt:source, but again, since
tt:source has @condition, it could be handled using my original proposal.

**Comment by mikedo** [comment] 2017-02-11 18:43
I've been thinking about this some more...while it is still the case we'd need to provide more signaling to support stereo pairs of images....just because we could do that, maybe we shouldn't. Although we don't constrain their content, the purpose of images in TT is to enable authoring control over glyph rendering. It would be unusual to enable 3D during the font rendering (where the glyph itself is rendered in 3D within the image).  I'm thinking now that this goes beyond what the industry really needs and tts:disparity on a single image is adequate. Further, both television and cinema groups at SMPTE a few years back found that text (captions, subtitles, scrolls, overlays, etc) had to remain at a fixed depth during a program as viewers disliked varying depth both spatially and temporally. These findings suggest that the utility of true stereo images for text may not actually be useful. I'm inclined to drop this exploration I started.

**Comment by palemieux** [comment] 2017-03-08 22:38
> I'm thinking now that this goes beyond what the industry really needs and tts:disparity on a single image is adequate. 

+1 in the context of TTML2.

**Comment by nigelmegitt** [comment] 2017-03-09 11:13
> Further, both television and cinema groups at SMPTE a few years back found that text (captions, subtitles, scrolls, overlays, etc) had to remain at a fixed depth during a program as viewers disliked varying depth both spatially and temporally. 

This is not a big thing for the BBC right now, but I think it is worth noting that there is not general consensus on this point: it is the opposite of the research I reviewed which found that in 3D presentations static depth text is offputting and causes focus difficulties - the solution preferred is to animate the depth and position of text so that it moves with the speaker, if you imagine a scene in which a person walks towards the audience while speaking, for example.

**Comment by nigelmegitt** [comment] 2017-03-09 11:16
Just to clarify:

>> I'm thinking now that this goes beyond what the industry really needs and tts:disparity on a single image is adequate.

>+1 in the context of TTML2.

I also am happy with this - as @skynavga has pointed out the same effect can in principle be generated using `condition`; I believe we do not have to specify any particular parameters in TTML2 to allow this to happen. So "less is more" probably applies here.

**Comment by skynavga** [comment] 2017-03-09 16:44
From [2017-03-09 Meeting], GA to add named condition parameters to permit doing this in a standard way with @condition.

**Comment by palemieux** [comment] 2017-03-09 16:52
> From [2017-03-09 Meeting], GA to add named condition parameters to permit doing this in a standard way with @condition.

How did the group go from `tts:disparity` to `@condition`

**Comment by nigelmegitt** [comment] 2017-03-09 17:41
@palemieux Early on there was a proposal from @skynavga that stereoscopic selection of images in TTML2 could be achieved by conditionally sending "left" images to the left display and "right" images to the right display, using `@condition`. Even if we take out `tts:disparity` on images this option remains. Then the question was, do we need named parameters in the standard or can we defer to specific implementations. I do not mind either way; @skynavga prefers named parameters. There seems to be no cost associated with adding them; my only concern is if it increases the number of tests required at CR for a feature that may never be used in practice.

**Comment by nigelmegitt** [comment] 2017-03-16 15:27
[Meeting 2017-03-16] Group agrees to make no change here and close the issue.

**Closed by nigelmegitt** 2017-03-16 15:27 UTC
Labels: question
