### ISSUE TITLE
Should background of a span be height of text in line or computed lineHeight?

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml2#101] opened 2015-11-04 18:57 UTC
TTML1SE says that lineHeight "is used to specify a style property that defines the inter-baseline separation between line areas" However it is unclear what the height of the line areas is, for the purpose of drawing the background as specified on a span. Is it identical to the computed line height, or is it related to the height of the line areas created based on the text contained within the span, independent of the baseline separation of those line areas?

The XSL-FO line area definition [1] appears to be relevant, though I'm not sure if it resolves the question.

[1] http://www.w3.org/TR/2006/REC-xsl11-20061205/#area-line 

We need to address this additionally for any mapping to HTML/CSS because it appears that a simple mapping of TTML concepts into CSS could introduce 'no background paint' areas in between lines.

If the two concepts may be computed to have different values this introduces the possibility that between two lines separated by e.g. a <br/> an empty 'no background paint' area may be introduced. I would argue that this is highly undesirable aesthetically when lineHeight is approximately the same as the line area height, e.g. in the range 80-125%. However if the two concepts must always have identical values this possibility would not arise; instead lines may be spaced far apart (for a large lineHeight) and the entire height would be painted with background colour. This latter option may also be undesirable in some use cases.

This issue is related to Issue-284.

(raised by Nigel Megitt on 2014-03-20)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/302

**Comment by nigelmegitt** [comment] 2016-12-16 16:19
Issue-284 is #87.

I have raised this issue as discussed at TPAC with CSSWG; the issue is https://github.com/w3c/csswg-drafts/issues/814

**Comment by nigelmegitt** [comment] 2016-12-17 21:39
This is closely related to, if not a duplicate of, #150.

**Comment by skynavga** [comment] 2017-05-13 20:14
Incorporate resolution of these comments into #150 and closing this issue.

**Closed by skynavga** 2017-05-13 20:14 UTC
