### ISSUE TITLE
Profiles cannot permit xml:base on ttp:features while prohibiting xml:base elsewhere.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#834] opened 2018-06-16 03:57 UTC
In TTML2, both `#base` and `#base-version-2` imply support for `xml:base` on `ttp:features`.

It is therefore not possible for a profile of TTML2 to match TTML1, and allow `xml:base` on `ttp:features`, through `#profiles`, while disallowing `xml:base` elsewhere.

Suggest excluding `xml:base` on `ttp:features` and `ttp:extensions` from `#base-version-2`.

**Comment by skynavga** [comment] 2018-06-16 04:35
We could do this, but it would make `#base-version-2` unique in the sense that it would not extend `#base`. I can live with that as a special case exception to other `#...-version-2` features. @nigelmegitt what say you?

**Comment by skynavga** [comment] 2018-06-16 04:49
On the other hand, perhaps it would be better to remove `#base` and change the name of `#base-version-2` to `#base-general`, redefining the latter as all uses of `xml:base` other than on `ttp:features` and `ttp:extensions`.

**Comment by skynavga** [comment] 2018-06-16 04:56
Or, we could leave `#base` in place, add `#base-general`, then redefine `#base-version-2` as `#base` + `#base-general`.

**Comment by nigelmegitt** [comment] 2018-06-18 10:20
I'm  struggling to understand the issue here. TTML1 [`#profile`](https://www.w3.org/TR/ttml1/#parameter-vocabulary-profile) requires support for `xml:base` in `ttp:features` and `ttp:extensions`; `#profile` is available in TTML2, defined as per TTML1. `#base` also specifies the subset of `#profile` that relates to `xml:base` use in `ttp:features` and `ttp:extensions`, so in that sense it is perhaps unnecessary.

Let's truth table it to see what options are available:

`xml:base` on `ttp:features and `ttp:extensions` | `xml:base` everywhere else | TTML1 | TTML2
-------------------------------- | ------------- | ------ | -----
No|No| `-#profile` | `-#base`, `-#profile`, `-#base-version-2` 
Yes|No| `+#profile` | `+#base`, `+#profile`, `-#base-version-2` **<- is this a contradiction?**
No|Yes| `-#profile` (there is no 'everwhere else') | `-#base`, `-#profile`, `+#base-version-2` **<- is this a contradiction?**
Yes|Yes| `+#profile` (there is no 'everwhere else') | `+#base`, `+#profile`, `+#base-version-2` 

If the issue here is the ambiguity or inconsistency caused by having different permissions for `#base` and `#base-version-2` for the second and third rows of the table, then my preferred solution would be to define `#base-content-not-profile` and make that be use of `xml:base` except on `ttp:features` and `ttp:extensions`, and then make `#base-version-2` be the sum of `#base` and `#base-content-not-profile`.

A less preferable way to achieve a similar result would be to add a rule (even editorially as a note, maybe?) saying that when the permissions for `#base` and `#base-version-2` differ then the setting for `#base` acts as an exception to the setting for `#base-version-2`, i.e. overriding the setting but explicitly for `ttp:features` and `ttp:extensions`.

**Comment by nigelmegitt** [comment] 2018-06-18 10:21
Just to clarify, my preferred suggestion is the one @skynavga proposed at https://github.com/w3c/ttml2/issues/834#issuecomment-397786926

**Comment by skynavga** [comment] 2018-06-18 14:38
@nigelmegitt @palemieux and I discussed and also agreed on https://github.com/w3c/ttml2/issues/834#issuecomment-397786926, so it seems we have consensus; I will post a PR today

**Comment by skynavga** [comment] 2018-06-22 03:16
Merged early per WG resolution.

**Closed** 2018-06-22 03:15 UTC
Labels: pr open, substantive
